(function(){
const c=window.MDAI_CONFIG||{},$=s=>document.querySelector(s),KEY="mdai-simple-projects-v1",state={project:null,scope:null,code:"",count:0,busy:false};
const client=c.supabaseUrl&&c.supabasePublishableKey?{functions:{async invoke(name,{body}){const r=await fetch(`${c.supabaseUrl}/functions/v1/${name}`,{method:"POST",headers:{apikey:c.supabasePublishableKey,Authorization:`Bearer ${c.supabasePublishableKey}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),context=r.clone(),data=await r.json().catch(()=>({}));return r.ok?{data,error:null}:{data:null,error:{message:data.error||"The service is unavailable",context}}}}}:null;
const esc=v=>String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function code(v){const x=String(v||"").toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,12);return[x.slice(0,4),x.slice(4,8),x.slice(8)].filter(Boolean).join("-")}
function recent(){try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x.filter(v=>v?.code&&v?.name).slice(0,12):[]}catch{return[]}}
function save(p,x){localStorage.setItem(KEY,JSON.stringify([{id:p.id,name:p.name,code:code(x),openedAt:Date.now()},...recent().filter(v=>v.id!==p.id)].slice(0,12)));renderRecent()}
function renderRecent(){const rows=recent();$("#simple-recent").hidden=!rows.length;$("#simple-recent-projects").innerHTML=rows.map(p=>`<button type="button" data-simple-code="${esc(p.code)}"><strong>${esc(p.name)}</strong><span>Open →</span></button>`).join("");document.querySelectorAll("[data-simple-code]").forEach(b=>b.onclick=()=>open(b.dataset.simpleCode))}
async function api(action,extra={}){const r=await fetch(`${c.supabaseUrl}/functions/v1/project-intake`,{method:"POST",headers:{apikey:c.supabasePublishableKey,Authorization:`Bearer ${c.supabasePublishableKey}`,"Content-Type":"application/json"},body:JSON.stringify({action,...extra})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Project service is unavailable");return p}
function enter(p){state.project=p.project;state.scope=p.upload_scope;state.code=code(p.project_code);state.count=Number(p.evidence_count||0);save(state.project,state.code);$("#simple-intake-landing").hidden=true;$("#simple-project").hidden=false;$("#simple-project-name").textContent=state.project.name;$("#simple-project-code").textContent=state.code;$("#simple-project-state").textContent=state.count?`${state.count} evidence file${state.count===1?"":"s"} already stored`:"Ready for evidence";$("#simple-upload-list").innerHTML="";$("#simple-upload-complete").hidden=true;$("#simple-add-more").hidden=true;$("#simple-add-evidence").hidden=false}
async function create(name){const b=$("#simple-create-submit"),m=$("#simple-create-message");b.disabled=true;b.textContent="Creating…";m.textContent="";try{const p=await api("create",{project_name:name});$("#simple-create-dialog").close();enter(p)}catch(e){m.textContent=e.message}finally{b.disabled=false;b.textContent="Create project"}}
async function open(x){const b=$("#simple-open-submit"),m=$("#simple-open-message");b.disabled=true;b.textContent="Opening…";m.textContent="";try{const p=await api("open",{project_code:code(x)});if($("#simple-open-dialog").open)$("#simple-open-dialog").close();enter(p)}catch(e){m.textContent=e.message;if(!$("#simple-open-dialog").open)$("#simple-open-dialog").showModal()}finally{b.disabled=false;b.textContent="Open project"}}
function metadata(file){if(!file.type.startsWith("video/"))return Promise.resolve({});return new Promise(resolve=>{const u=URL.createObjectURL(file),v=document.createElement("video"),done=(x={})=>{URL.revokeObjectURL(u);resolve(x)};v.preload="metadata";v.onloadedmetadata=()=>{const r=v.videoWidth/Math.max(1,v.videoHeight);done({duration_seconds:Number(v.duration||0),width:Number(v.videoWidth||0),height:Number(v.videoHeight||0),projection:r>=1.9&&r<=2.1?"equirectangular":"unknown"})};v.onerror=()=>done();v.src=u})}
function kind(f,m){const n=f.name.toLowerCase();if(f.type==="application/pdf"||n.endsWith(".pdf"))return"Project document";if(n.endsWith(".insv"))return"Insta360 source video";if(n.endsWith(".insp"))return"Insta360 source photo";if(n.endsWith(".lrv"))return"Insta360 preview video";if(f.type.startsWith("image/"))return"Photo evidence";if(f.type.startsWith("video/")&&m.projection==="equirectangular")return"360 capture";return f.type.startsWith("video/")?"Video evidence":"Project evidence"}
async function upload(list){const files=[...list];if(!files.length||state.busy)return;if(!client||!window.MDAIObjectStorage){$("#simple-project-state").textContent="Secure upload service is unavailable. Reload and try again.";return}state.busy=true;$("#simple-add-evidence").hidden=true;$("#simple-upload-complete").hidden=true;$("#simple-add-more").hidden=true;$("#simple-upload-list").innerHTML=files.map((f,i)=>`<article><span class="simple-upload-icon">${f.type.startsWith("video/")?"▶":f.type.startsWith("image/")?"▧":"DOC"}</span><div><strong>${esc(f.name)}</strong><small data-st="${i}">Waiting</small><div><i data-bar="${i}"></i></div></div><b data-pct="${i}">0%</b></article>`).join("");let done=0;
try{for(let i=0;i<files.length;i++){const f=files[i],st=document.querySelector(`[data-st="${i}"]`),bar=document.querySelector(`[data-bar="${i}"]`),pct=document.querySelector(`[data-pct="${i}"]`),meta=await metadata(f);await window.MDAIObjectStorage.upload({client,entityType:"evidence",organizationId:state.scope.organization_id,propertyId:state.scope.property_id,spaceId:state.scope.space_id,projectAccess:{code:state.code},file:f,metadata:{media_type:kind(f,meta),captured_at:new Date(f.lastModified||Date.now()).toISOString(),source_metadata:{...meta,source:"passwordless-studio",original_last_modified:f.lastModified||null}},onProgress:u=>{const n=Number(u.percent||0);st.textContent=u.stage==="finalizing"?"Securing original…":u.stage==="complete"?"Uploaded":u.label;bar.style.width=`${n}%`;pct.textContent=`${n}%`}});done++}const result=await api("submit",{project_code:state.code});state.count=Number(result.evidence_count||state.count+done);$("#simple-project-state").textContent=`${state.count} evidence file${state.count===1?"":"s"} stored`;$("#simple-complete-copy").textContent=`${done} file${done===1?"":"s"} uploaded. The originals are safely stored and ready for processing.`;$("#simple-upload-complete").hidden=false;$("#simple-add-more").hidden=false}catch(e){$("#simple-project-state").textContent=`Upload stopped: ${e.message}`;$("#simple-add-more").textContent="Try again or add evidence";$("#simple-add-more").hidden=false}finally{state.busy=false;$("#simple-evidence-files").value=""}}
function landing(){$("#simple-intake").hidden=false;$("#simple-intake-landing").hidden=false;$("#simple-project").hidden=true;$("#prototype-gate").hidden=true;renderRecent()}
$("#simple-create-project").onclick=()=>{$("#simple-create-form").reset();$("#simple-create-message").textContent="";$("#simple-create-dialog").showModal()};$("#simple-open-project").onclick=()=>{$("#simple-open-form").reset();$("#simple-open-message").textContent="";$("#simple-open-dialog").showModal()};$("#simple-create-form").onsubmit=e=>{e.preventDefault();create($("#simple-project-name-input").value.trim())};$("#simple-open-form").onsubmit=e=>{e.preventDefault();open($("#simple-project-code-input").value)};$("#simple-project-code-input").oninput=e=>e.target.value=code(e.target.value);document.querySelectorAll("[data-simple-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.simpleClose).close());$("#simple-evidence-files").onchange=e=>upload(e.target.files);$("#simple-add-more").onclick=()=>$("#simple-evidence-files").click();$("#simple-project-back").onclick=landing;$("#simple-team-sign-in").onclick=()=>{$("#simple-intake").hidden=true;$("#prototype-gate").hidden=false};renderRecent();window.MDAIProjectIntake={showLanding:landing,hide:()=>$("#simple-intake").hidden=true};
})();
