import { safeError } from "../_shared/safe-error.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const origins=new Set(["https://measureddecision.ai","https://www.measureddecision.ai","https://measureddecision.com","https://www.measureddecision.com","http://localhost:8080","http://127.0.0.1:8080"]);
function cors(r:Request){const o=r.headers.get("origin")||"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"https://measureddecision.ai","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"}}
function json(r:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(m:string,s=400):never{throw Object.assign(new Error(m),{status:s})}
function clean(v:unknown,n=120){return typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,n):""}
function code(v:unknown){return String(v||"").toUpperCase().replace(/[^A-Z2-9]/g,"")}
function hex(b:Uint8Array){return Array.from(b).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hash(v:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))))}
function newCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",b=crypto.getRandomValues(new Uint8Array(12)),x=Array.from(b,n=>a[n%a.length]).join("");return `${x.slice(0,4)}-${x.slice(4,8)}-${x.slice(8)}`}
Deno.serve(async(r)=>{if(r.method==="OPTIONS")return new Response("ok",{headers:cors(r)});if(r.method!=="POST")return json(r,{error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json(r,{error:"Server configuration is incomplete"},500);const db=createClient(url,key,{auth:{persistSession:false}});
 const caller=(r.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||r.headers.get("cf-connecting-ip")||"unknown")+"|"+(r.headers.get("user-agent")||"unknown");
 try{const body=await r.json(),action=clean(body?.action,30);
  /* A project code is twelve characters from a 32-symbol alphabet, so guessing
     one is not a realistic attack. Guessing is still worth refusing to sit
     through: only *failed* attempts consume a slot, so somebody working through
     codes stops after twenty a day while a person opening their own project
     twice an hour is never touched. */
  async function failedAttempt(){const slot=await db.rpc("consume_project_intake_create_slot",{p_request_key_hash:await hash(`intake-open-miss|${caller}`),p_daily_limit:20});if(!slot.error&&slot.data===false)fail("Too many incorrect project codes from this device today. Try again tomorrow.",429)}
  async function access(){const c=code(body?.project_code);if(c.length!==12){await failedAttempt();fail("Enter the 12-character project code",401)}const{data,error}=await db.from("project_intake_access").select("*").eq("code_hash",await hash(c)).maybeSingle();if(error)throw error;if(!data||data.status==="closed"){await failedAttempt();fail("Project not found",404)}return data}
  async function payload(a:any){const[p,e]=await Promise.all([db.from("properties").select("id,name,created_at").eq("id",a.property_id).single(),db.from("evidence_items").select("id",{count:"exact",head:true}).eq("project_intake_access_id",a.id).is("deleted_at",null)]);if(p.error)throw p.error;if(e.error)throw e.error;return{project:p.data,upload_scope:{organization_id:a.organization_id,property_id:a.property_id,space_id:a.default_space_id,access_id:a.id},evidence_count:Number(e.count||0),status:a.status}}
  if(action==="create"){const name=clean(body?.project_name);if(name.length<2)fail("Enter a project name");const ip=r.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||r.headers.get("cf-connecting-ip")||"unknown";const slot=await db.rpc("consume_project_intake_create_slot",{p_request_key_hash:await hash(`${ip}|${r.headers.get("user-agent")||"unknown"}`),p_daily_limit:10});if(slot.error)throw slot.error;if(!slot.data)fail("Too many projects were created from this device today. Open an existing project or try again tomorrow.",429);
   const s=await db.from("project_intake_settings").select("organization_id,owner_user_id").eq("id",true).maybeSingle();if(s.error)throw s.error;if(!s.data)fail("Public project intake has not been configured",503);const c=newCode();const p=await db.from("properties").insert({organization_id:s.data.organization_id,name,address:{profile:{project_type:"other",intake_source:"passwordless-studio"}},access_classification:"private",created_by:s.data.owner_user_id}).select("id,name,created_at").single();if(p.error||!p.data)throw p.error||new Error("Project could not be created");
   const sp=await db.from("spaces").insert({organization_id:s.data.organization_id,property_id:p.data.id,name:"Unsorted evidence",building:"Project",level:"Evidence intake",review_state:"needs_review",created_by:s.data.owner_user_id}).select("id").single();if(sp.error||!sp.data){await db.from("properties").delete().eq("id",p.data.id);throw sp.error||new Error("Project evidence area could not be created")}
   const a=await db.from("project_intake_access").insert({organization_id:s.data.organization_id,property_id:p.data.id,default_space_id:sp.data.id,code_hash:await hash(code(c)),created_by:s.data.owner_user_id}).select("*").single();if(a.error||!a.data){await db.from("properties").delete().eq("id",p.data.id);throw a.error||new Error("Project access could not be created")};await db.from("audit_events").insert({organization_id:s.data.organization_id,actor_id:null,action:"project_intake.created",entity_type:"properties",entity_id:p.data.id,detail:{source:"passwordless-studio"}});return json(r,{...(await payload(a.data)),project_code:c})}
  if(action==="open"){const a=await access();await db.from("project_intake_access").update({last_opened_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",a.id);return json(r,{...(await payload(a)),project_code:clean(body?.project_code,20).toUpperCase()})}
  if(action==="submit"){const a=await access(),e=await db.from("evidence_items").select("id",{count:"exact",head:true}).eq("project_intake_access_id",a.id).is("deleted_at",null);if(e.error)throw e.error;if(!e.count)fail("Add at least one evidence file before submitting");const now=new Date().toISOString();await db.from("project_intake_access").update({status:"submitted",submitted_at:now,updated_at:now}).eq("id",a.id);await db.from("audit_events").insert({organization_id:a.organization_id,actor_id:null,action:"project_intake.submitted",entity_type:"properties",entity_id:a.property_id,detail:{evidence_count:e.count}});return json(r,{submitted:true,evidence_count:e.count})}fail("Unsupported action",404)
 }catch(e){const safe=safeError(e,"The project service could not complete that request.");return json(r,safe.body,safe.status)}});
